# include app from custom-source
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: networkpolicies-akrugliak
  namespace: flux-system
spec:
  interval: 0m10s
  targetNamespace: akrugliak
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/cluster-002/custom-resources/akrugliak/networkpolicies
  prune: true
  wait: true
  timeout: 2m0s
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-variables
        # Use this ConfigMap if it exists, but proceed if it doesn't.
        optional: false
    substitute:
      KUBE_POD_IP_CIDR: "10.0.0.0/28"
      KUBE_POD_IP_CIDR_2: "10.0.1.0/28"
