---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx-ingress-1
  namespace: akrugliak
spec:
  patches:
  - patch: |

      - op: replace
        path: /metadata/name
        value: nginx-ingress-1
      - op: replace
        path: /spec/releaseName
        value: nginx-ingress-1
    target:
      kind: HelmRelease
      name: nginx-ingress
  interval: 5m
  retryInterval: 1m
  timeout: 15m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./clusters/cluster-002/custom-resources/akrugliak/nginx-ingress-1
  prune: true
  wait: true
