---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: akrugliak
spec:
  # releaseName: nginx-ingress-1
  targetNamespace: akrugliak
  storageNamespace: akrugliak
  chart:
    spec:
      version: 1.4.0
  values:
