---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: gke-template
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/gke-template
  prune: false
  wait: true
  timeout: 15m
  # patches:
  #   # patch to set some password to admin user in weave
  #   - patch: |
  #       - op: replace
  #         path: /spec/values/adminUser/passwordHash
  #         value: $2y$08$ojvUSnmVscqVNJMWPaCQ6.OBoCLsR/fb3t9E00rBjswjLP.Ow97tO
  #     target:
  #       kind: HelmRelease
  #       name: weave-gitops
