---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kafka-alerts
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: prometheus
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/ksemele-demo-gke/custom-resources/kafka-alerts
  prune: false
  wait: true
  timeout: 15m0s
