---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
- repo: https://github.com/markdownlint/markdownlint
  rev: v0.13.0
  hooks:
  - id: markdownlint
    name: Markdownlint
    description: Run markdownlint on your Markdown files
    entry: mdl --style .mdl.rb
    language: ruby
    files: \.(md|mdown|markdown)$
- repo: local
  hooks:
  - id: check-kustomization-paths
    name: Check kustomization paths
    description: This hook checks if given resource paths in kustomization.yaml files exist.
    language: python
    entry: python3 check-kustomization-paths.py
    files: kustomization.yaml$
    exclude: 'examples/.*'
    types: [file, yaml]
    additional_dependencies: [pyyaml, termcolor]
