---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../components/flux/prod/gotk-components.yaml
  # - cluster-variables.yaml  # I applied this configmap manually, in reality it should be generated and apply by terraform
  - gotk-sync.yaml
  - repos.yaml
  - weave.yaml
  - networkpolicies.yaml
