---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: weave-gitops-ingress
  namespace: flux-system
spec:
  policyTypes:
    - Ingress
  ingress:
    - from:
        - ipBlock:
            cidr: ${PRIVATE_IP_CIDR:=10.0.0.0/8}
  podSelector:
    matchLabels:
      app.kubernetes.io/name: weave-gitops
