---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - ../../../common-template
  - ../../../policy-templates/allow-egress-internet.yaml
  - ../../../policy-templates/allow-egress-from-all-to-private-network.yaml
  - ../../../policy-templates/allow-ingress-from-private-network-to-all.yaml
