---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: networkpolicies-kube-system
  namespace: flux-system
spec:
  interval: 0m10s
  targetNamespace: kube-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./components/networkpolicies/namespace-templates/kube-system/gke
  prune: true
  wait: true
  timeout: 2m0s
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-variables
        # Use this ConfigMap if it exists, but proceed if it doesn't.
        optional: false
