---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: flux-system
spec:
  interval: 0m10s
  targetNamespace: <NAMESPACE>
  storageNamespace: <NAMESPACE>
  chart:
    spec:
      chart: nginx
      version: 18.2.3
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 5m0s
