apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/component: rabbitmq-operator
    app.kubernetes.io/name: rabbitmq-system
    app.kubernetes.io/part-of: rabbitmq
  name: rabbitmq-system-2
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rabbitmq-cluster-operator-2
  namespace: flux-system   # we put HelmRelease resources into flux namespace to make use of secretRef with Git credentials
spec:
  interval: 1h0m0s
  releaseName: rabbitmq-cluster-operator-2
  targetNamespace: rabbitmq-system-2   # the namespace where Helm chart gets deployed
  storageNamespace: rabbitmq-system-2
  chart:
    spec:
      chart: rabbitmq-cluster-operator
      version: 2.7.1
      sourceRef:
        kind: HelmRepository
        name: rabbitmq-repo
        namespace: flux-system
