#Source: https://github.com/rabbitmq/cluster-operator/tree/main/docs/examples/production-ready
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
  namespace: s005
spec:
  image: 'docker.io/bitnami/rabbitmq:3.10.7-debian-11-r3'
  service:
  replicas: 1
  terminationGracePeriodSeconds: 5 # 604800 default
  resources:
    requests:
      cpu: 1
      memory: 1Gi
    limits:
      cpu: 1
      memory: 1Gi
  rabbitmq:
    additionalConfig: |
      cluster_partition_handling = autoheal
      vm_memory_high_watermark_paging_ratio = 0.99
      disk_free_limit.relative = 1.0
      collect_statistics_interval = 10000
      log.file.level = info
      prometheus.return_per_object_metrics = true
