---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: flux-system
spec:
  releaseName: prometheus
  chart:
    spec:
      version: 65.x
  values:
