apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-2
  namespace: akrugliak
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Devoops Conference 2024</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                display: flex;
                justify-content: center;
                align-items: center;
                height: 100vh;
                margin: 0;
                background-color: #f4f4f9;
            }

            h1 {
                color: #333;
            }
        </style>
    </head>

    <body>
        <h1>Hello Devoops Conference 2024!</h1>
    </body>

    </html>
