---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../../components/apps/nginx
  - configmap.yaml
patches:
  - path: helm-release.yaml
    target:
      kind: HelmRelease
      name: nginx
