---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: flux-system
spec:
  interval: 0m10s
  targetNamespace: <NAMESPACE>
  storageNamespace: <NAMESPACE>
  chart:
    spec:
      chart: nginx-ingress
      version: 1.4.0
      sourceRef:
        kind: HelmRepository
        name: nginx-stable
        namespace: flux-system
      interval: 5m0s
