---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: flux-system
spec:
  interval: 5m
  releaseName: postgresql
  targetNamespace: <NAMESPACE>
  storageNamespace: <NAMESPACE>
  chart:
    spec:
      chart: postgresql
      version: 15.2.0
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    global:
      storageClass: ""
    auth:
      enablePostgresUser: true
      existingSecret: ""
    primary:
      service:
        type: "ClusterIP"
        ports:
          postgresql: 5432
        loadBalancerIP: ""
      persistence:
        enabled: true
        size: 100Mi
