---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../../components/apps/weave
patches:
  - path: helm-release.yaml
    target:
      kind: HelmRelease
      name: weave-gitops
