---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prometheus-rules
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: prometheus
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/common/monitoring/prometheus-rules
  prune: true
  wait: true
  timeout: 5m0s
