---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - ../../../common-template
  - ../../../policy-templates/allow-egress-internet.yaml
  - ../../../policy-templates/allow-ingress-from-cluster-to-all.yaml
  - allow-egress-from-konnectivity-agent-to-all.yaml
  - allow-egress-from-kube-system-to-gcp-specific.yaml
  - allow-egress-from-metrics-server-to-kubelet.yaml
  - allow-ingress-from-all-to-metrics-server.yaml
  - ../allow-ingress-from-all-to-kube-api.yaml
  - ../allow-ingress-from-all-to-kube-dns.yaml
  - ../allow-ingress-from-prometheus-to-kube-dns.yaml
  - ../allow-ingress-from-prometheus-to-kube-proxy.yaml
