---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: master
  # secretRef:  # if you use private repo - you need to add secret to access to it
  #   name: flux-git-auth
  url: https://github.com/ksemele/fluxv2-test.git
  # # If you are know what you do, you can include other repo as dependencies... but I don't recommend:
  # include:
  #   - repository:
  #       name: base
# ---
# apiVersion: source.toolkit.fluxcd.io/v1beta2
# kind: GitRepository
# metadata:
#   name: base
#   namespace: flux-system
# spec:
#   interval: 1m0s
#   ref:
#     branch: feature/flux-test
#   url: https://bitbucket.org/demo/your-awesome-repo.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/ksemele-demo-gke
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
