---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - helm-release.yaml
  - repo.yaml
  - networkpolicy.yaml
configMapGenerator:
  - name: flux-kube-state-metrics-config
    files:
      - flux-kube-state-metrics-config.yaml
    options:
      labels:
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: monitoring
configurations:
  - kustomizeconfig.yaml
